<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobOfferSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('job_offers')->insert([
            [
                'company_id' => 1,
                'job_category_id' => 1,
                'job_area_id' => 4,
                'posting_start' => '2022/08/18',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集',
                'employment_status' => '正社員',
                'salary' => '25万円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容01',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 2,
                'job_category_id' => 2,
                'job_area_id' => 10,
                'posting_start' => '2022/08/26',
                'posting_end' => '2022/09/08',
                'is_publish' => true,
                'title' => '人材募集02',
                'employment_status' => '正社員、パート',
                'salary' => '25万円、パート：時給1,000円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容02',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。02',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 18,
                'posting_start' => '2022/08/12',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 1,
                'posting_start' => '2022/08/1',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 5,
                'job_category_id' => 4,
                'job_area_id' => 2,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'ライターさんを募集します！',
                'employment_status' => 'パート',
                'salary' => '時給1,000円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => '医療系のライティングをお願いします。',
                'welfare' => '有給',
                'holiday' => '週3日〜OK',
                'qualification' => '',
                'recruitment_count' => 3,
                'free_text' => '医療系の知識がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 4,
                'job_category_id' => 5,
                'job_area_id' => 3,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'Webマーケターを募集します！',
                'employment_status' => '契約社員',
                'salary' => '月給18万円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => 'アクセス解析や顧客対応をお願いします。',
                'welfare' => '社会保険完備、有給',
                'holiday' => '土日祝',
                'qualification' => '',
                'recruitment_count' => 1,
                'free_text' => 'ご自身でブログを運営されてるなどの経験がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 1,
                'job_area_id' => 5,
                'posting_start' => '2022/08/18',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集',
                'employment_status' => '正社員',
                'salary' => '25万円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容01',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 2,
                'job_category_id' => 2,
                'job_area_id' => 6,
                'posting_start' => '2022/08/26',
                'posting_end' => '2022/09/08',
                'is_publish' => true,
                'title' => '人材募集02',
                'employment_status' => '正社員、パート',
                'salary' => '25万円、パート：時給1,000円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容02',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。02',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 7,
                'posting_start' => '2022/08/12',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 8,
                'posting_start' => '2022/08/1',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 5,
                'job_category_id' => 4,
                'job_area_id' => 9,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'ライターさんを募集します！',
                'employment_status' => 'パート',
                'salary' => '時給1,000円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => '医療系のライティングをお願いします。',
                'welfare' => '有給',
                'holiday' => '週3日〜OK',
                'qualification' => '',
                'recruitment_count' => 3,
                'free_text' => '医療系の知識がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 4,
                'job_category_id' => 5,
                'job_area_id' => 10,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'Webマーケターを募集します！',
                'employment_status' => '契約社員',
                'salary' => '月給18万円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => 'アクセス解析や顧客対応をお願いします。',
                'welfare' => '社会保険完備、有給',
                'holiday' => '土日祝',
                'qualification' => '',
                'recruitment_count' => 1,
                'free_text' => 'ご自身でブログを運営されてるなどの経験がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 1,
                'job_area_id' =>11,
                'posting_start' => '2022/08/18',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集',
                'employment_status' => '正社員',
                'salary' => '25万円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容01',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 2,
                'job_category_id' => 2,
                'job_area_id' => 12,
                'posting_start' => '2022/08/26',
                'posting_end' => '2022/09/08',
                'is_publish' => true,
                'title' => '人材募集02',
                'employment_status' => '正社員、パート',
                'salary' => '25万円、パート：時給1,000円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容02',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。02',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 13,
                'posting_start' => '2022/08/12',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 14,
                'posting_start' => '2022/08/1',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 5,
                'job_category_id' => 4,
                'job_area_id' => 15,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'ライターさんを募集します！',
                'employment_status' => 'パート',
                'salary' => '時給1,000円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => '医療系のライティングをお願いします。',
                'welfare' => '有給',
                'holiday' => '週3日〜OK',
                'qualification' => '',
                'recruitment_count' => 3,
                'free_text' => '医療系の知識がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 4,
                'job_category_id' => 5,
                'job_area_id' => 16,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'Webマーケターを募集します！',
                'employment_status' => '契約社員',
                'salary' => '月給18万円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => 'アクセス解析や顧客対応をお願いします。',
                'welfare' => '社会保険完備、有給',
                'holiday' => '土日祝',
                'qualification' => '',
                'recruitment_count' => 1,
                'free_text' => 'ご自身でブログを運営されてるなどの経験がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 1,
                'job_area_id' => 17,
                'posting_start' => '2022/08/18',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集',
                'employment_status' => '正社員',
                'salary' => '25万円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容01',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 2,
                'job_category_id' => 2,
                'job_area_id' => 18,
                'posting_start' => '2022/08/26',
                'posting_end' => '2022/09/08',
                'is_publish' => true,
                'title' => '人材募集02',
                'employment_status' => '正社員、パート',
                'salary' => '25万円、パート：時給1,000円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容02',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。02',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 19,
                'posting_start' => '2022/08/12',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 20,
                'posting_start' => '2022/08/1',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 5,
                'job_category_id' => 4,
                'job_area_id' => 21,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'ライターさんを募集します！',
                'employment_status' => 'パート',
                'salary' => '時給1,000円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => '医療系のライティングをお願いします。',
                'welfare' => '有給',
                'holiday' => '週3日〜OK',
                'qualification' => '',
                'recruitment_count' => 3,
                'free_text' => '医療系の知識がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 4,
                'job_category_id' => 5,
                'job_area_id' => 22,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'Webマーケターを募集します！',
                'employment_status' => '契約社員',
                'salary' => '月給18万円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => 'アクセス解析や顧客対応をお願いします。',
                'welfare' => '社会保険完備、有給',
                'holiday' => '土日祝',
                'qualification' => '',
                'recruitment_count' => 1,
                'free_text' => 'ご自身でブログを運営されてるなどの経験がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 2,
                'job_category_id' => 2,
                'job_area_id' => 18,
                'posting_start' => '2022/08/26',
                'posting_end' => '2022/09/08',
                'is_publish' => true,
                'title' => '人材募集02',
                'employment_status' => '正社員、パート',
                'salary' => '25万円、パート：時給1,000円',
                'job_time' => '9:00〜18:00',
                'job_content' => '仕事内容02',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。02',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 19,
                'posting_start' => '2022/08/12',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 1,
                'job_category_id' => 3,
                'job_area_id' => 20,
                'posting_start' => '2022/08/1',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => '人材募集03',
                'employment_status' => '契約社員',
                'salary' => '25万円',
                'job_time' => '10:00〜19:00',
                'job_content' => '仕事内容03',
                'welfare' => '有給',
                'holiday' => '土日祝',
                'qualification' => '普通自動車運転免許',
                'recruitment_count' => 5,
                'free_text' => 'テスト投稿です。03',
                'created_at' => '2022/08/01 11:11:11',
            ],
            [
                'company_id' => 5,
                'job_category_id' => 4,
                'job_area_id' => 21,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'ライターさんを募集します！',
                'employment_status' => 'パート',
                'salary' => '時給1,000円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => '医療系のライティングをお願いします。',
                'welfare' => '有給',
                'holiday' => '週3日〜OK',
                'qualification' => '',
                'recruitment_count' => 3,
                'free_text' => '医療系の知識がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
            [
                'company_id' => 4,
                'job_category_id' => 5,
                'job_area_id' => 23,
                'posting_start' => '2022/08/20',
                'posting_end' => '2022/09/30',
                'is_publish' => true,
                'title' => 'Webマーケターを募集します！',
                'employment_status' => '契約社員',
                'salary' => '月給18万円〜',
                'job_time' => '10:00〜19:00',
                'job_content' => 'アクセス解析や顧客対応をお願いします。',
                'welfare' => '社会保険完備、有給',
                'holiday' => '土日祝',
                'qualification' => '',
                'recruitment_count' => 1,
                'free_text' => 'ご自身でブログを運営されてるなどの経験がある方は歓迎します！',
                'created_at' => '2022/08/19 11:11:11',
            ],
        ]);
    }
}
